spring:
  application:
    name: RegistrationService
  jpa:
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/ClinickAuthentication
    username: postgres
    password: purvesh
    driver-class-name: org.postgresql.Driver

server:
  port: 8888

administartion:
  Number: 9145522040
  Password: purvesh
