spring:
  application:
    name: admin-service
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate.format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/clinick
    username: root
    password: Krishnani@7634
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081

